<?php
session_start();
require_once('tcpdf/tcpdf.php');
include 'DB_connection.php';

if (!isset($_GET['id'])) {
    die("Meeting ID is required.");
}

$meeting_id = intval($_GET['id']); // Sanitize input

// Fetch meeting details
$sql = "SELECT * FROM meetings WHERE id = :meeting_id";
$stmt = $conn->prepare($sql);
$stmt->bindParam(':meeting_id', $meeting_id, PDO::PARAM_INT);
$stmt->execute();
$meeting = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$meeting) {
    die("Meeting not found.");
}

// Fetch all tasks
$sql = "SELECT * FROM tasks";
$stmt = $conn->prepare($sql);
$stmt->execute();
$tasks = $stmt->fetchAll(PDO::FETCH_ASSOC);

// ✅ Fetch attendance using username directly (since user_id is NULL)
$sql = "SELECT username, attended 
        FROM attendance 
        WHERE meeting_id = :meeting_id";
$stmt = $conn->prepare($sql);
$stmt->bindParam(':meeting_id', $meeting_id, PDO::PARAM_INT);
$stmt->execute();
$attendance = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Create PDF
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('MOM Tracker');
$pdf->SetTitle('Minutes of Meeting - ' . $meeting['title']);
$pdf->SetMargins(20, 20, 20);
$pdf->AddPage();

// Header
$pdf->SetFont('helvetica', 'B', 18);
$pdf->Cell(0, 12, 'Minutes of Meeting', 0, 1, 'C');
$pdf->Ln(4);
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(0, 8, 'Generated on: ' . date("d M Y, h:i A"), 0, 1, 'R');

// Line
$pdf->Ln(2);
$pdf->SetDrawColor(50, 50, 50);
$pdf->Line(20, $pdf->GetY(), 190, $pdf->GetY());
$pdf->Ln(5);

// Meeting Info
$pdf->SetFont('helvetica', 'B', 13);
$pdf->Cell(0, 10, 'Meeting Details', 0, 1);

$pdf->SetFont('helvetica', '', 11);
$pdf->MultiCell(0, 7, "Title: " . $meeting['title'], 0, 'L');
$pdf->MultiCell(0, 7, "Date & Time: " . date("d M Y, h:i A", strtotime($meeting['date_time'])), 0, 'L');
$pdf->MultiCell(0, 7, "Agenda: " . $meeting['agenda'], 0, 'L');

// Participants
$pdf->Ln(3);
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 8, 'Participants:', 0, 1);

$pdf->SetFont('helvetica', '', 11);
$members = explode(',', $meeting['assigned_users']);
foreach ($members as $member) {
    $pdf->Cell(0, 6, '- ' . trim($member), 0, 1);
}

// ✅ Attendance Section (now working)
$pdf->Ln(5);
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 10, 'Attendance:', 0, 1);

$pdf->SetFont('helvetica', '', 11);
if (!empty($attendance)) {
    foreach ($attendance as $att) {
        $status = $att['attended'] ? 'Present' : 'Absent';
        $pdf->Cell(0, 6, '- ' . $att['username'] . ' (' . $status . ')', 0, 1);
    }
} else {
    $pdf->Cell(0, 6, 'No attendance data recorded.', 0, 1);
}

// Notes Section
$pdf->Ln(3);
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 8, 'Meeting Notes:', 0, 1);

$pdf->SetFont('helvetica', '', 11);
$pdf->MultiCell(0, 7, !empty($meeting['notes']) ? $meeting['notes'] : 'No notes recorded.', 0, 'L');

// Tasks Section
$pdf->Ln(3);
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 8, 'All Tasks:', 0, 1);

$pdf->SetFont('helvetica', '', 11);
if (!empty($tasks)) {
    foreach ($tasks as $task) {
        $assigned = !empty($task['assigned_to']) ? $task['assigned_to'] : 'Unassigned';
        $dueDate = !empty($task['due_date']) ? date("d M Y", strtotime($task['due_date'])) : 'No Due Date';

        $pdf->MultiCell(0, 7, "• " . $task['title'] . "\n    Assigned to: " . $assigned . "\n    Due Date: " . $dueDate, 0, 'L');
        $pdf->Ln(1);
    }
} else {
    $pdf->Cell(0, 6, 'No tasks available.', 0, 1);
}

// Footer
$pdf->Ln(10);
$pdf->SetFont('helvetica', 'I', 10);
$pdf->Cell(0, 10, 'Generated by MOM Tracker', 0, 0, 'C');

// Output PDF
$pdf->Output('Meeting_Report_' . $meeting_id . '.pdf', 'D');
?>
